name: Free VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cài SSH & Ngrok
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl wget unzip
          sudo systemctl enable ssh
          sudo systemctl start ssh
          echo "root:123456" | sudo chpasswd
          sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
          sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config
          sudo systemctl restart ssh

          # Cài ngrok
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          ./ngrok config add-authtoken 30BK1LcGMDkvzdYQt6grWvbJuTn_NtEgUu9JmPQwPo9KsHiP
          ./ngrok tcp 22 > ngrok.log &
          sleep 15
          curl -s http://127.0.0.1:4040/api/tunnels
