name: Free VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cài đặt Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          chmod +x ngrok
          ./ngrok config add-authtoken 30BK1LcGMDkvzdYQt6grWvbJuTn_NtEgUu9JmPQwPo9KsHiP

      - name: Mở SSH qua Ngrok
        run: ./ngrok tcp 22
