name: Free VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH + Ngrok
      run: |
        sudo apt update
        sudo apt install -y openssh-server curl wget unzip
        sudo systemctl enable ssh
        sudo systemctl start ssh
        echo 'root:123456' | sudo chpasswd
        sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        sudo service ssh restart

        wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip
        unzip ngrok-stable-linux-amd64.zip
        chmod +x ngrok
        ./ngrok authtoken 30BK1LcGMDkvzdYQt6grWvbJuTn_NtEgUu9JmPQwPo9KsHiP
        ./ngrok tcp 22 &
        sleep 10
        curl -s localhost:4040/api/tunnels | grep -o 'tcp://[^"]*'
